services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend 
    ports:
      - 8080:8080

  redis:
    image: redis
    command: "redis-server --save 60 1 --loglevel warning"
    restart: unless-stopped

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp:/var/lib/postgresql/data

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend 
    ports: 
      - 5000:5000

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_HOST=localhost
    ports:
      - 80:80

