services:

  backend:
    build: 
      context: .
      dockerfile: back.Dockerfile
    ports: 
      - 8080:8080

  frontend:
    build: 
      context: .
      dockerfile: front.Dockerfile
    ports: 
      - 5000:5000
