name: Release NodeJS app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout to the repository
    - uses: actions/checkout@v3
    
    - name: Docker hub login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./part3/express-app
        push: true
        tags: carotene110/dockermooc-express-app:latest

